package com.gjorgjimarkov.caffeineperday;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by gjorgjim on 6/6/16.
 */
public class DataDrinks {

    public static ArrayList<ParentDrink> getList() {

        ArrayList<ParentDrink> arrayList = new ArrayList<>();
        ArrayList<Drinks> cofee = new ArrayList<>();
        ArrayList<Drinks> soda = new ArrayList<>();
        ArrayList<Drinks> tea = new ArrayList<>();
        ArrayList<Drinks> energy = new ArrayList<>();

        cofee.add(new Drinks("Americano Coffee","360ml",154, R.drawable.cofee,0));
        cofee.add(new Drinks("Arby's Jamocha Shake","480ml",12,R.drawable.cofee,0));
        cofee.add(new Drinks("Barista Bros Iced Coffee","510ml",219,R.drawable.cofee,0));
        cofee.add(new Drinks("Baskin Robbins Cappuccino Blast","720ml",234,R.drawable.cofee,0));
        cofee.add(new Drinks("Bean and Body Coffee","240ml",72,R.drawable.cofee,0));
        cofee.add(new Drinks("Biggby Brewed Coffee","480ml",200,R.drawable.cofee,0));
        cofee.add(new Drinks("Biggby Creamy Lattes","480ml",100,R.drawable.cofee,0));
        cofee.add(new Drinks("Biggby Espresso","60ml",100,R.drawable.cofee,0));
        cofee.add(new Drinks("Biggby Frozen Lattes","480ml",182,R.drawable.cofee,0));
        cofee.add(new Drinks("Biggby Iced Coffee","480ml",192,R.drawable.cofee,0));
        cofee.add(new Drinks("Black Medicine Iced Coffee","330ml",206,R.drawable.cofee,0));
        cofee.add(new Drinks("Bulletproof Coffee","240ml",145,R.drawable.cofee,0));
        cofee.add(new Drinks("Caffe Mocha","360ml",152,R.drawable.cofee,0));
        cofee.add(new Drinks("Caffe Nero Coffee","360ml",80,R.drawable.cofee,0));
        cofee.add(new Drinks("Cappuccino","360ml",154,R.drawable.cofee,0));
        cofee.add(new Drinks("Caribou Brewed Coffee","480ml",305,R.drawable.cofee,0));
        cofee.add(new Drinks("Chick-fill-A Iced Coffee","360ml",94,R.drawable.cofee,0));
        cofee.add(new Drinks("Coffee (Brewed)","240ml",163,R.drawable.cofee,0));
        cofee.add(new Drinks("Coffee (Brewed,Decaf)","240ml",6,R.drawable.cofee,0));
        cofee.add(new Drinks("Coffee (Espresso)","45ml",77,R.drawable.cofee,0));
        cofee.add(new Drinks("Coffee (Instant)","240ml",57,R.drawable.cofee,0));
        cofee.add(new Drinks("Costa Coffee","450ml",277,R.drawable.cofee,0));
        cofee.add(new Drinks("Dare Iced Coffee","500ml",160,R.drawable.cofee,0));
        cofee.add(new Drinks("Death Wish Coffee","360ml",660,R.drawable.cofee,0));
        cofee.add(new Drinks("Dunkin' Donuts Brewed Coffee","480ml",302,R.drawable.cofee,0));
        cofee.add(new Drinks("Dunkin' Donuts Dunkaccino","420ml",106,R.drawable.cofee,0));
        cofee.add(new Drinks("Dunkin' Donuts Iced Coffee","720ml",295,R.drawable.cofee,0));
        cofee.add(new Drinks("Dunkin' Donuts Iced Latte","720ml",97,R.drawable.cofee,0));
        cofee.add(new Drinks("Dunkin' Donuts Latte","480ml",97,R.drawable.cofee,0));
        cofee.add(new Drinks("Dunkin' Donuts Mocha","480ml",97,R.drawable.cofee,0));
        cofee.add(new Drinks("Dutch Bros. Coffee","600ml",256,R.drawable.cofee,0));
        cofee.add(new Drinks("Einstein Bros Coffee","480ml",206,R.drawable.cofee,0));
        cofee.add(new Drinks("High Brew Coffee","240ml",163,R.drawable.cofee,0));
        cofee.add(new Drinks("Illy Issimo Cafe","210ml",155,R.drawable.cofee,0));
        cofee.add(new Drinks("International Delight Iced Coffee","240ml",65,R.drawable.cofee,0));
        cofee.add(new Drinks("K-Cup Coffee","240ml",120,R.drawable.cofee,0));
        cofee.add(new Drinks("Latte","480ml",154,R.drawable.cofee,0));
        cofee.add(new Drinks("Long Black","180ml",154,R.drawable.cofee,0));
        cofee.add(new Drinks("Macchiato","240ml",150,R.drawable.cofee,0));
        cofee.add(new Drinks("Macchiato","480ml",225,R.drawable.cofee,0));
        cofee.add(new Drinks("McDonalds Latte","480ml",142,R.drawable.cofee,0));
        cofee.add(new Drinks("McDonalds Mocha","480ml",167,R.drawable.cofee,0));
        cofee.add(new Drinks("McDonalds Coffee","480ml",145,R.drawable.cofee,0));
        cofee.add(new Drinks("NESCAFÉ","320ml",130,R.drawable.cofee,0));
        cofee.add(new Drinks("Nescafe Ice Java","27ml",100,R.drawable.cofee,0));
        cofee.add(new Drinks("Panera Bread Coffee","480ml",189,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Brewed Coffee","480ml",267,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Caffe Americano","480ml",140,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Caffe Latte","480ml",140,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Caffe Mocha","480ml",165,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Caffe Cappuccino","480ml",140,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Coffee Espresso","45ml",70,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Iced Coffee","480ml",150,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Iced Latte","480ml",140,R.drawable.cofee,0));
        cofee.add(new Drinks("Peet's Iced Mocha","480ml",165,R.drawable.cofee,0));
        cofee.add(new Drinks("Robusta Coffee","240ml",265,R.drawable.cofee,0));
        cofee.add(new Drinks("Seattle's Best Brewed Coffee","360ml",260,R.drawable.cofee,0));
        cofee.add(new Drinks("Shock Coffee Triple Latte","240ml",231,R.drawable.cofee,0));
        cofee.add(new Drinks("Skinny Cow Iced Coffee","240ml",70,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Bottled Frappuccino","285ml",90,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Bottled Iced Coffee","330ml",115,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Cold Brew Coffee","480ml",200,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Decaf Coffee","480ml",25,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Doubleshot","195ml",125,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Grand Coffee Americano","480ml",225,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Grand Coffee Latte","480ml",150,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Grand Coffee Mocha","480ml",175,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Grand Coffee Cappuccino","480ml",150,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Grand Coffee","480ml",330,R.drawable.cofee,0));
        cofee.add(new Drinks("Starbucks Latte Macchiato","480ml",225,R.drawable.cofee,0));
        cofee.add(new Drinks("Stumptown Cold Brew + Milk","480ml",319,R.drawable.cofee,0));
        cofee.add(new Drinks("Stumptown Cold Brew Chocolate + Milk","480ml",340,R.drawable.cofee,0));
        cofee.add(new Drinks("Stumptown Cold Brew Coffee","300ml",279,R.drawable.cofee,0));
        cofee.add(new Drinks("Tim Hortons Large Brewed Coffee","600ml",200,R.drawable.cofee,0));
        cofee.add(new Drinks("Tim Hortons Small English Toffee Coffee","300ml",60,R.drawable.cofee,0));
        cofee.add(new Drinks("Tim Hortons Small French Vanilla Coffee","300ml",60,R.drawable.cofee,0));
        cofee.add(new Drinks("Turkish Coffee","60ml",50,R.drawable.cofee,0));

        soda.add(new Drinks("7-Up","360ml",0,R.drawable.soda,0));
        soda.add(new Drinks("A&W Cream Soda","360ml",29,R.drawable.soda,0));
        soda.add(new Drinks("Afri Cola","360ml",89,R.drawable.soda,0));
        soda.add(new Drinks("Ale 8 1","360ml",37,R.drawable.soda,0));
        soda.add(new Drinks("Barq's Root Beer","360ml",22,R.drawable.soda,0));
        soda.add(new Drinks("Bawls","300ml",64,R.drawable.soda,0));
        soda.add(new Drinks("Bawls Cherry","480ml",100,R.drawable.soda,0));
        soda.add(new Drinks("Bawls Exxtra","480ml",150,R.drawable.soda,0));
        soda.add(new Drinks("Bawls Orange","480ml",64,R.drawable.soda,0));
        soda.add(new Drinks("Bawls Root Beer","480ml",100,R.drawable.soda,0));
        soda.add(new Drinks("Big Red Soda","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Blink Energy Water","500ml",150,R.drawable.soda,0));
        soda.add(new Drinks("Caffeinated Club Soda","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Cheerwine","360ml",48,R.drawable.soda,0));
        soda.add(new Drinks("Cherry Coke","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Cherry Coke Zero","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Coca-Cola Classic","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Coca-Cola Zero","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Coca-Cola Life","360ml",28,R.drawable.soda,0));
        soda.add(new Drinks("Coke Zero","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Diet A&W Cream Soda","360ml",22,R.drawable.soda,0));
        soda.add(new Drinks("Diet Cheerwine","360ml",48,R.drawable.soda,0));
        soda.add(new Drinks("Diet Cherry Coca-Cola","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Diet Coke","360ml",46,R.drawable.soda,0));
        soda.add(new Drinks("Diet Dr Pepper","360ml",41,R.drawable.soda,0));
        soda.add(new Drinks("Diet Pepsi","360ml",34,R.drawable.soda,0));
        soda.add(new Drinks("Diet Mountain Dew","360ml",54,R.drawable.soda,0));
        soda.add(new Drinks("Diet RC Cola","360ml",47,R.drawable.soda,0));
        soda.add(new Drinks("Diet Vanilla Coke","360ml",45,R.drawable.soda,0));
        soda.add(new Drinks("Dr Pepper","360ml",41,R.drawable.soda,0));
        soda.add(new Drinks("Dr Pepper 10","360ml",51,R.drawable.soda,0));
        soda.add(new Drinks("Dr Pepper Cherry","360ml",39,R.drawable.soda,0));
        soda.add(new Drinks("Fanta","360ml",0,R.drawable.soda,0));
        soda.add(new Drinks("Faygo Cola","360ml",42,R.drawable.soda,0));
        soda.add(new Drinks("Faygo Moon Mist","360ml",20,R.drawable.soda,0));
        soda.add(new Drinks("Flatt Cola","240ml",65,R.drawable.soda,0));
        soda.add(new Drinks("Fritz Cola","330ml",83,R.drawable.soda,0));
        soda.add(new Drinks("Hansen's Diet Red","240ml",57,R.drawable.soda,0));
        soda.add(new Drinks("Honest Professor Fizz","360ml",40,R.drawable.soda,0));
        soda.add(new Drinks("Inca Kola","500ml",50,R.drawable.soda,0));
        soda.add(new Drinks("Mello Yello","360ml",51,R.drawable.soda,0));
        soda.add(new Drinks("Mountain Dew","360ml",54,R.drawable.soda,0));
        soda.add(new Drinks("Mountain Dew Baja Blast","480ml",72,R.drawable.soda,0));
        soda.add(new Drinks("Mountain Dew Black Label","480ml",83,R.drawable.soda,0));
        soda.add(new Drinks("Mountain Dew Game Fuel","600ml",121,R.drawable.soda,0));
        soda.add(new Drinks("Mountain Dew Live Wire","360ml",54,R.drawable.soda,0));
        soda.add(new Drinks("Mountain Dew Voltage","360ml",55,R.drawable.soda,0));
        soda.add(new Drinks("PC Cola","360ml",12,R.drawable.soda,0));
        soda.add(new Drinks("Pepsi Cola","360ml",38,R.drawable.soda,0));
        soda.add(new Drinks("Pepsi Max","360ml",69,R.drawable.soda,0));
        soda.add(new Drinks("RC Cola","360ml",43,R.drawable.soda,0));
        soda.add(new Drinks("Slurpee","480ml",40,R.drawable.soda,0));
        soda.add(new Drinks("Vanilla Coke","360ml",34,R.drawable.soda,0));


        tea.add(new Drinks("Arizona Iced Tea","600ml",38,R.drawable.tea,0));
        tea.add(new Drinks("Big Train Spiced Chai","240ml",65,R.drawable.tea,0));
        tea.add(new Drinks("Biggby Iced Tea","480ml",38,R.drawable.tea,0));
        tea.add(new Drinks("Brown Rice Tea","240ml",4,R.drawable.tea,0));
        tea.add(new Drinks("Chai Tea","240ml",50,R.drawable.tea,0));
        tea.add(new Drinks("Crystal Light Iced Tea","240ml",11,R.drawable.tea,0));
        tea.add(new Drinks("Dunkin' Donuts Iced Tea","750ml",81,R.drawable.tea,0));
        tea.add(new Drinks("Fast Lane Black Tea","240ml",110,R.drawable.tea,0));
        tea.add(new Drinks("Fuze Iced Tea","600ml",20,R.drawable.tea,0));
        tea.add(new Drinks("Gold Peak Tea","540ml",27,R.drawable.tea,0));
        tea.add(new Drinks("Green Tea","510ml",60,R.drawable.tea,0));
        tea.add(new Drinks("Guayaki Canned Yerba Mate","480ml",150,R.drawable.tea,0));
        tea.add(new Drinks("Guayaki Yerba Mate Bottled Tea","480ml",140,R.drawable.tea,0));
        tea.add(new Drinks("Guayusa Tea","240ml",66,R.drawable.tea,0));
        tea.add(new Drinks("Honest Tea","510ml",90,R.drawable.tea,0));
        tea.add(new Drinks("Inko's White Tea Energy","450ml",184,R.drawable.tea,0));
        tea.add(new Drinks("K Cup Tea","240ml",41,R.drawable.tea,0));
        tea.add(new Drinks("Kombucha Tea","240ml",24,R.drawable.tea,0));
        tea.add(new Drinks("Lipton Brisk Tea","360ml",8,R.drawable.tea,0));
        tea.add(new Drinks("Lipton Iced Tea","600ml",48,R.drawable.tea,0));
        tea.add(new Drinks("Lipton Natural Energy Tea","240ml",75,R.drawable.tea,0));
        tea.add(new Drinks("Lipton Tea","240ml",55,R.drawable.tea,0));
        tea.add(new Drinks("Matcha Tea","240ml",70,R.drawable.tea,0));
        tea.add(new Drinks("McDonalds Sweet Tea","960ml",100,R.drawable.tea,0));
        tea.add(new Drinks("Morning Thunder Tea","240ml",40,R.drawable.tea,0));
        tea.add(new Drinks("Nestea Iced Tea","600ml",13,R.drawable.tea,0));
        tea.add(new Drinks("Oi Ocha Green Tea","510ml",60,R.drawable.tea,0));
        tea.add(new Drinks("Oprah Chai Tea Latte","480ml",50,R.drawable.tea,0));
        tea.add(new Drinks("Oregon Chai Tea","120ml",33,R.drawable.tea,0));
        tea.add(new Drinks("Pacific Chai","360ml",100,R.drawable.tea,0));
        tea.add(new Drinks("Peace Tea","780ml",60,R.drawable.tea,0));
        tea.add(new Drinks("Pure Leaf Iced Tea","550ml",57,R.drawable.tea,0));
        tea.add(new Drinks("Red Rose Energy Tea","240ml",60,R.drawable.tea,0));
        tea.add(new Drinks("Sencha Green Tea Shot","200ml",40,R.drawable.tea,0));
        tea.add(new Drinks("Snapple Tea","480ml",42,R.drawable.tea,0));
        tea.add(new Drinks("SoBe Green Tea","600ml",10,R.drawable.tea,0));
        tea.add(new Drinks("Southern Sweat Tea","480ml",41,R.drawable.tea,0));
        tea.add(new Drinks("Taiwanese Milk Tea","400ml",130,R.drawable.tea,0));
        tea.add(new Drinks("Tazo Chai","240ml",47,R.drawable.tea,0));
        tea.add(new Drinks("Tea (Black)","240ml",42,R.drawable.tea,0));
        tea.add(new Drinks("Tea (Decaf)","240ml",5,R.drawable.tea,0));
        tea.add(new Drinks("Tea (Herbal)","240ml",0,R.drawable.tea,0));
        tea.add(new Drinks("Tea (Iced)","240ml",47,R.drawable.tea,0));
        tea.add(new Drinks("Tea (Instant)","240ml",40,R.drawable.tea,0));
        tea.add(new Drinks("Tea (Jasmine)","240ml",25,R.drawable.tea,0));
        tea.add(new Drinks("Tea (Oolong)","240ml",37,R.drawable.tea,0));
        tea.add(new Drinks("Tea (White)","240ml",28,R.drawable.tea,0));
        tea.add(new Drinks("Teas' Tea Oolong","500ml",55,R.drawable.tea,0));
        tea.add(new Drinks("Teavana Tea","240ml",41,R.drawable.tea,0));
        tea.add(new Drinks("Tejava Iced Tea","360ml",50,R.drawable.tea,0));
        tea.add(new Drinks("Turkey Hill Iced Tea","480ml",110,R.drawable.tea,0));
        tea.add(new Drinks("Twig Tea (Kukicha)","240ml",25,R.drawable.tea,0));
        tea.add(new Drinks("Wendy's Iced Tea)","480ml",32,R.drawable.tea,0));
        tea.add(new Drinks("Xingtea Flavored Tea","700ml",35,R.drawable.tea,0));
        tea.add(new Drinks("Xingtea Just Plain Tea","700ml",75,R.drawable.tea,0));
        tea.add(new Drinks("Yellow Tea","240ml",33,R.drawable.tea,0));
        tea.add(new Drinks("Yerba Mate Tea","240ml",85,R.drawable.tea,0));
        tea.add(new Drinks("Zest Highly Caffeinated Tea","240ml",150,R.drawable.tea,0));


        energy.add(new Drinks("28 Black Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("3 Water","500ml",50,R.drawable.energy,0));
        energy.add(new Drinks("4C Energy Liquid Water Enhancers","240ml",60,R.drawable.energy,0));
        energy.add(new Drinks("4C Energy Rush","240ml",80,R.drawable.energy,0));
        energy.add(new Drinks("ABB Diet Turbo","540ml",90,R.drawable.energy,0));
        energy.add(new Drinks("Ace Energy Drink","240ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Acute Fruit Energy Drink","450ml",213,R.drawable.energy,0));
        energy.add(new Drinks("Advocare Slim","240ml",120,R.drawable.energy,0));
        energy.add(new Drinks("Alsa Energy Drink","480ml",100,R.drawable.energy,0));
        energy.add(new Drinks("Amp Energy Cherry Blast","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Amp Energy Drink","480ml",142,R.drawable.energy,0));
        energy.add(new Drinks("Amp Energy Zero","480ml",157,R.drawable.energy,0));
        energy.add(new Drinks("Amp Passion Fruit","480ml",156,R.drawable.energy,0));
        energy.add(new Drinks("Amp Strawberry Limeade","480ml",156,R.drawable.energy,0));
        energy.add(new Drinks("Aqua Enerviva","600ml",100,R.drawable.energy,0));
        energy.add(new Drinks("Arbonne Energy Fizz Stick","240ml",50,R.drawable.energy,0));
        energy.add(new Drinks("Archer Farms Energy Drink","360ml",100,R.drawable.energy,0));
        energy.add(new Drinks("Arizona Arnolnd Palmer Half and Half","690ml",43,R.drawable.energy,0));
        energy.add(new Drinks("Arizona Caution Energy Drink","340ml",144,R.drawable.energy,0));
        energy.add(new Drinks("Arizona Natural Energy","450ml",120,R.drawable.energy,0));
        energy.add(new Drinks("Arma Energy Drink","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Arriba Horchata Energy","330ml",76,R.drawable.energy,0));
        energy.add(new Drinks("Atomic Blast","480ml",100,R.drawable.energy,0));
        energy.add(new Drinks("Avitae Caffeinated Water","500ml",125,R.drawable.energy,0));
        energy.add(new Drinks("AZ Energy Drink","450ml",188,R.drawable.energy,0));
        energy.add(new Drinks("B 63 Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("BANG Energy Drink","480ml",300,R.drawable.energy,0));
        energy.add(new Drinks("Battery Energy Drink","350ml",106,R.drawable.energy,0));
        energy.add(new Drinks("Battery Juiced Energ Drink","450ml",144,R.drawable.energy,0));
        energy.add(new Drinks("Beaver Buzz Energy Drink","250ml",110,R.drawable.energy,0));
        energy.add(new Drinks("Berocca","240ml",90,R.drawable.energy,0));
        energy.add(new Drinks("Berzerk Energy Drink","480ml",225,R.drawable.energy,0));
        energy.add(new Drinks("Big Jak Energy Drink","480ml",164,R.drawable.energy,0));
        energy.add(new Drinks("Bigelow Tea","240ml",45,R.drawable.energy,0));
        energy.add(new Drinks("Bing Energy Drink","360ml",120,R.drawable.energy,0));
        energy.add(new Drinks("Black Bruin Energy Drink","250ml",38,R.drawable.energy,0));
        energy.add(new Drinks("Blade Energy Drink","480ml",240,R.drawable.energy,0));
        energy.add(new Drinks("Blood Energy Potion","100ml",80,R.drawable.energy,0));
        energy.add(new Drinks("BLU Energy Drinks","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Blu Frog Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Blue Bolt","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Blue Charge","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Blue Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Bomb Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Bomba Energy Drink","250ml",75,R.drawable.energy,0));
        energy.add(new Drinks("Boost Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Booty Sweet Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Brawndo Energy Drink","480ml",200,R.drawable.energy,0));
        energy.add(new Drinks("Bulldog Buzz","330ml",204,R.drawable.energy,0));
        energy.add(new Drinks("Burn Energy Drink","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Buzz Monkey","250ml",78,R.drawable.energy,0));
        energy.add(new Drinks("BuzzWater","500ml",200,R.drawable.energy,0));
        energy.add(new Drinks("Caffeine Energy Drink","360ml",140,R.drawable.energy,0));
        energy.add(new Drinks("Cannabis Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Celsius Energy Drink","360ml",200,R.drawable.energy,0));
        energy.add(new Drinks("Cintron Energy Drink","480ml",170,R.drawable.energy,0));
        energy.add(new Drinks("Brawndo Energy Drink","480ml",200,R.drawable.energy,0));
        energy.add(new Drinks("Club Mate","500ml",100,R.drawable.energy,0));
        energy.add(new Drinks("CoMotion","250ml",280,R.drawable.energy,0));
        energy.add(new Drinks("Courage Energy Drink","250ml",50,R.drawable.energy,0));
        energy.add(new Drinks("Cran Energy Juice","300ml",69,R.drawable.energy,0));
        energy.add(new Drinks("Crave Energy Drink","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Crunk Energy Drink","480ml",192,R.drawable.energy,0));
        energy.add(new Drinks("Dark Dog Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Demon Energy Drink","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Diablo Energy Drink","250ml",95,R.drawable.energy,0));
        energy.add(new Drinks("Divas Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("DNA Energy Drink","480ml",170,R.drawable.energy,0));
        energy.add(new Drinks("Duff Energy Drink","360ml",120,R.drawable.energy,0));
        energy.add(new Drinks("Eboost Energy Drink","240ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Enorm Energy Drink","250ml",88,R.drawable.energy,0));
        energy.add(new Drinks("Ex Energy Drink","250ml",79,R.drawable.energy,0));
        energy.add(new Drinks("Fire Blade Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Fuel Energy Drink","480ml",240,R.drawable.energy,0));
        energy.add(new Drinks("Full Throttle Energy Drink","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("GaGa Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Golazo Sports Energy Drink","360ml",100,R.drawable.energy,0));
        energy.add(new Drinks("Grazzhopper Energy Drink","250ml",63,R.drawable.energy,0));
        energy.add(new Drinks("Hard Rock Energy Drink","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Havoc Energy Drink","250ml",52,R.drawable.energy,0));
        energy.add(new Drinks("Heroec Energy Water","500ml",60,R.drawable.energy,0));
        energy.add(new Drinks("Hype Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Inc","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Java Monster","450ml",188,R.drawable.energy,0));
        energy.add(new Drinks("Kick Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("KX Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Lift Plus Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Liquid Lightning","480ml",200,R.drawable.energy,0));
        energy.add(new Drinks("Luquid Ninja Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("M-150 Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Mad Croc Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Mario Power Up Energy Drink","250ml",120,R.drawable.energy,0));
        energy.add(new Drinks("Mega Monster Energy Drink","720ml",240,R.drawable.energy,0));
        energy.add(new Drinks("Missile Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Monster Absolutely Zero","480ml",140,R.drawable.energy,0));
        energy.add(new Drinks("Monster Assault","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Monster Cuba Lima","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Monster DUB","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Monster Energy Drink","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Monster Export","250ml",76,R.drawable.energy,0));
        energy.add(new Drinks("Monster Extra Strength","360ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Monster Import","500ml",179,R.drawable.energy,0));
        energy.add(new Drinks("Monster Khaos","480ml",154,R.drawable.energy,0));
        energy.add(new Drinks("Monster Lo-Carb","480ml",140,R.drawable.energy,0));
        energy.add(new Drinks("Monster Mixxd Energy Drink","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Monster Pink Energy Drink","480ml",140,R.drawable.energy,0));
        energy.add(new Drinks("Monster Rehab Energy Drink","450ml",161,R.drawable.energy,0));
        energy.add(new Drinks("Monster Ripper","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Monster The Doctor Energy Drink","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Monster Ultra Citron","480ml",152,R.drawable.energy,0));
        energy.add(new Drinks("Monster Ultra Energy Drink","480ml",140,R.drawable.energy,0));
        energy.add(new Drinks("Monster Ultra Sunride","480ml",151,R.drawable.energy,0));
        energy.add(new Drinks("Morning Spark Energy Drink","500ml",170,R.drawable.energy,0));
        energy.add(new Drinks("Mother Energy Drink","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Mother Inferno","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("NEO Energy Drink","250ml",100,R.drawable.energy,0));
        energy.add(new Drinks("Neon Energy Drink","250ml",100,R.drawable.energy,0));
        energy.add(new Drinks("Nerd Energy Drink","360ml",120,R.drawable.energy,0));
        energy.add(new Drinks("No Fear Energy Drink","480ml",182,R.drawable.energy,0));
        energy.add(new Drinks("NOS Energy Drink","480ml",160,R.drawable.energy,0));
        energy.add(new Drinks("OK Energy Drink","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Positive Charge Energy Drink","500ml",150,R.drawable.energy,0));
        energy.add(new Drinks("Power Horse Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Race Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull Blue Edition","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull Cherry Edition","360ml",114,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull Orange Edition","360ml",114,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull Red Edition","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull Silver Edition","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull Sugar Free","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull Total Zero","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Bull Yellow Edition","360ml",114,R.drawable.energy,0));
        energy.add(new Drinks("Red Pain Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Rooster","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Red Thunder Energy Drink","250ml",75,R.drawable.energy,0));
        energy.add(new Drinks("Reize Energy Drink","250ml",50,R.drawable.energy,0));
        energy.add(new Drinks("Relentless Energy Drink","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Rize Energy Drink","250ml",60,R.drawable.energy,0));
        energy.add(new Drinks("Roaring Lion Energy Drink","500ml",161,R.drawable.energy,0));
        energy.add(new Drinks("Robust Energy Drink","250ml",79,R.drawable.energy,0));
        energy.add(new Drinks("Shark Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Slammers Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Source Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Spartan Energy Drink","250ml",90,R.drawable.energy,0));
        energy.add(new Drinks("SPIKE Shooter","250ml",300,R.drawable.energy,0));
        energy.add(new Drinks("T-Licious Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("TEHO Energy Drink","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("Tiger Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Ubermonster Energy Brew","500ml",160,R.drawable.energy,0));
        energy.add(new Drinks("UPTIME Energy Drink","250ml",100,R.drawable.energy,0));
        energy.add(new Drinks("Vegas Fuel Energy Drink","250ml",75,R.drawable.energy,0));
        energy.add(new Drinks("White Tiger","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Wicked Hammer Energy","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("Wildcat Energy Drink","250ml",80,R.drawable.energy,0));
        energy.add(new Drinks("X Ray Energy Drink","250ml",79,R.drawable.energy,0));

        ParentDrink coffee = new ParentDrink("Coffee", cofee);
        ParentDrink sodaa = new ParentDrink("Soda", soda );
        ParentDrink energyy = new ParentDrink("Energy Drink", energy);
        ParentDrink teaa = new ParentDrink("Tea",tea);

        arrayList.add(coffee);
        arrayList.add(sodaa);
        arrayList.add(energyy);
        arrayList.add(teaa);

        return arrayList;
    }

}
